[package]
name = "hub_util"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hub_util"

[lib]
name = "hub_util"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }